services:
  web:
    build: .
    container_name: ssh-updater
    restart: unless-stopped
    ports:
      - "8099:8080"
    environment:
      - TZ=Europe/Bucharest
      - MONGO_URL=mongodb://mongo:27017/sshupdater   # host = service name
      - JWT_SECRET=1FloareA1
    depends_on:
      - mongo
    # (optional) wait until mongo is healthy; see section 3

  mongo:
    image: mongo:4.4
    container_name: ssh-updater-mongo
    restart: unless-stopped
    command: ["--bind_ip_all"]
    ports:
      - "27017:27017"   # optional for host debugging; you can remove later
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 10

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: changeme
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
    depends_on:
      - mongo   

volumes:
  mongo_data:


